name: Build and Test

on:
  push:
    branches:
      - main
      - 'feature-*'
      - 'bugfix-*'
      - 'fix-*'
  pull_request:
    branches:
      - main
      - 'feature-*'
      - 'bugfix-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install requirements
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Install package in editable mode
        run: |
          source .venv/bin/activate
          pip install -e .

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
